services:
  nginx:
    image: nginx:latest
    ports:
      - "8093:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
      - ./src:/app
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    links:
      - db
    volumes:
      - ./src:/app
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "skeleton"
      POSTGRES_USER: "skeleton"
      POSTGRES_PASSWORD: "skeleton"
    ports:
      - "5432:5432"